---
abstract: 'Autocomplete of geolocation data from GeoNames'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ElasticSearchX-Autocomplete-GeoNames
requires:
  Carp: 0
  ElasticSearchX::Autocomplete: 0.06
  ElasticSearchX::Autocomplete::Util: 0
  Geo::Distance: 0
  List::MoreUtils: 0
  Text::CSV: 0
  Text::CSV_XS: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/clintongormley/ElasticSearchX-Autocomplete-GeoNames/issues
  repository: git://github.com/clintongormley/ElasticSearchX-Autocomplete-GeoNames.git
version: 0.06
