---
abstract: 'Autocomplete of geolocation data from GeoNames'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ElasticSearchX-Autocomplete-GeoNames
provides:
  ElasticSearchX::Autocomplete::GeoNames:
    file: lib/ElasticSearchX/Autocomplete/GeoNames.pm
    version: 0.03
  ElasticSearchX::Autocomplete::GeoNames::Admin:
    file: lib/ElasticSearchX/Autocomplete/GeoNames/Admin.pm
requires:
  ElasticSearchX::Autocomplete: 0.03
resources:
  bugtracker: https://github.com/clintongormley/ElasticSearchX-Autocomplete-GeoNames/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/clintongormley/ElasticSearchX-Autocomplete-GeoNames/
version: 0.03
